"""add_theme_region_icon_to_predefined_categories

Revision ID: 208986ebad35
Revises: 464b0f29ef3a
Create Date: <DATETIME>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208986ebad35'
down_revision: Union[str, None] = '464b0f29ef3a' # Set previous revision ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_categories', sa.Column('theme', sa.String(), nullable=True))
    op.create_index(op.f('ix_predefined_categories_theme'), 'predefined_categories', ['theme'], unique=False)
    op.add_column('predefined_categories', sa.Column('region', sa.String(), nullable=True))
    op.create_index(op.f('ix_predefined_categories_region'), 'predefined_categories', ['region'], unique=False)
    op.add_column('predefined_categories', sa.Column('icon_identifier', sa.String(), nullable=True))
    # No index needed for icon_identifier unless it's frequently queried directly
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predefined_categories_region'), table_name='predefined_categories')
    op.drop_column('predefined_categories', 'region')
    op.drop_index(op.f('ix_predefined_categories_theme'), table_name='predefined_categories')
    op.drop_column('predefined_categories', 'theme')
    op.drop_column('predefined_categories', 'icon_identifier')
    # ### end Alembic commands ###
